# Generated by Django 5.2.2 on 2025-08-23 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_schedules", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schedule",
            new_name="SeasonSchedule",
        ),
        migrations.RenameModel(
            old_name="GameClass",
            new_name="TeamDivision",
        ),
    ]
