# Generated by Django 5.2.2 on 2025-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_schedules", "0002_rename_schedule_seasonschedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="short_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
