# Generated by Django 5.2.2 on 2025-06-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("league", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="start of season")),
                ("end_date", models.DateTimeField(verbose_name="end of season")),
            ],
        ),
        migrations.CreateModel(
            name="TeamContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("player_count", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("field_name", models.CharField(max_length=200)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_us", models.CharField(max_length=200)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.division",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=200)),
                ("end_time", models.CharField(max_length=200)),
                ("date", models.DateTimeField(verbose_name="date of event")),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("practice", "practice"),
                            ("scrimmage", "scrimmage"),
                            ("game", "game"),
                            ("playoff", "playoff"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "field_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.field"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_role",
                    models.CharField(
                        choices=[
                            ("coach", "coach"),
                            ("ast. coach", "ast. coach"),
                            ("player", "player"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.team"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.teamcontact",
                    ),
                ),
            ],
        ),
    ]
