# Generated by Django 5.2.2 on 2025-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.DateTimeField(max_length=200),
        ),
    ]
