# Generated by Django 5.2.2 on 2025-06-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_season_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league.division'),
        ),
    ]
