# Generated by Django 5.2.2 on 2025-06-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0007_alter_season_division"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="division",
        ),
        migrations.AddField(
            model_name="division",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="league.season",
            ),
        ),
    ]
