# Generated by Django 5.2.2 on 2025-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_season_division_division_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='season',
        ),
        migrations.AddField(
            model_name='team',
            name='league_name',
            field=models.CharField(default='league name', max_length=200),
        ),
    ]
